print("основные этапы эволюции человека")
print("1.")
a = input()
print ("2.")
b = input()
print("3.")
c = input()
print ("4.")
d = input ()
print("5.")
f = input()
print ("6.")
g = input()
print (a,b,c,d,f,g,sep=" => ")